version: "3.8"
services: 
  myblog:
    build: ./client
    container_name: client_c
    ports: 
      - '8083:3000'
    volumes: 
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true